-- Chạy một lần sau khi Oracle tạo xong database (thư mục /opt/oracle/scripts/setup), bằng "sqlplus / as sysdba".
-- Ba schema, mỗi schema một bảng chứa số CCCD, để một CDE "Số CCCD" gắn vào ba cột ở ba bảng.
-- Dữ liệu cố ý có vi phạm; số lượng ghi ở comment để đối chiếu với kết quả kiểm thử.
WHENEVER SQLERROR EXIT SQL.SQLCODE
ALTER SESSION SET CONTAINER = ORCLPDB1;

-- Schema chỉ chứa dữ liệu, không đăng nhập được
CREATE USER core_kh NO AUTHENTICATION DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
CREATE USER crm     NO AUTHENTICATION DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
CREATE USER card    NO AUTHENTICATION DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
CREATE USER other   NO AUTHENTICATION DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

-- 1) core_kh.kh.cccd: VARCHAR2, 20 dòng
--    sai định dạng 12 chữ số: 3 dòng (1 NULL, 1 có chữ, 1 thiếu số); trùng: 0
CREATE TABLE core_kh.kh (
  id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ten  VARCHAR2(100) NOT NULL,
  cccd VARCHAR2(20)
);
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Nguyen Van A', '001201000001');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Tran Thi B',   '001201000002');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Le Van C',     '001201000003');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Pham Thi D',   '001201000004');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Hoang Van E',  '001201000005');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Vu Thi F',     '001201000006');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Dang Van G',   '001201000007');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Bui Thi H',    '001201000008');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Do Van I',     '001201000009');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Ngo Thi K',    '001201000010');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Duong Van L',  '001201000011');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Ly Thi M',     '001201000012');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Phan Van N',   '001201000013');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Vo Thi O',     '001201000014');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Truong Van P', '001201000015');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Dinh Thi Q',   '001201000016');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Ta Van R',     '001201000017');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Khong CCCD',   NULL);
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Co chu',       '00120100ABCD');
INSERT INTO core_kh.kh (ten, cccd) VALUES ('Thieu so',     '0012010');

-- 2) crm.customer.id_no: VARCHAR2, 15 dòng
--    sai định dạng: 2 dòng (1 NULL, 1 dài 13 số); trùng: 1 nhóm giá trị xuất hiện 2 lần
CREATE TABLE crm.customer (
  customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name   VARCHAR2(100) NOT NULL,
  id_no       VARCHAR2(20)
);
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH 01', '079301000001');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH 02', '079301000002');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH 03', '079301000003');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH 04', '079301000004');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH 05', '079301000005');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH 06', '079301000006');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH 07', '079301000007');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH 08', '079301000008');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH 09', '079301000009');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH 10', '079301000010');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH 11', '079301000011');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH trung 1', '079301000099');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH trung 2', '079301000099');
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH null', NULL);
INSERT INTO crm.customer (full_name, id_no) VALUES ('KH dai',  '0793010000123');

-- 3) card.holder.cccd: NUMBER(12) (kiểu số), 5 dòng
--    Kiểu dữ liệu không thuộc nhóm chuỗi: kiểm thử Regex sẽ bị đánh dấu "Không áp dụng"
CREATE TABLE card.holder (
  holder_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cccd      NUMBER(12)
);
INSERT INTO card.holder (cccd) VALUES (201201000001);
INSERT INTO card.holder (cccd) VALUES (201201000002);
INSERT INTO card.holder (cccd) VALUES (201201000003);
INSERT INTO card.holder (cccd) VALUES (201201000004);
INSERT INTO card.holder (cccd) VALUES (NULL);

-- Bảng không gắn CDE, để so sánh
CREATE TABLE other.branch (
  branch_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      VARCHAR2(100)
);
INSERT INTO other.branch (name) VALUES ('Chi nhanh 1');
INSERT INTO other.branch (name) VALUES ('Chi nhanh 2');
COMMIT;

-- Tài khoản chỉ đọc cho OpenMetadata (ingest metadata và chạy pipeline kiểm thử)
CREATE USER dq_reader IDENTIFIED BY "dq_reader_pw";
GRANT CREATE SESSION TO dq_reader;
GRANT SELECT_CATALOG_ROLE TO dq_reader;
GRANT SELECT ANY DICTIONARY TO dq_reader;
GRANT SELECT ON core_kh.kh      TO dq_reader;
GRANT SELECT ON crm.customer    TO dq_reader;
GRANT SELECT ON card.holder     TO dq_reader;
GRANT SELECT ON other.branch    TO dq_reader;
